import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './_components/footer/footer'
import Header from './_components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <div className="pb-6">
            <Header />
          </div>
          <div className="flex-1">{children}</div>
          <div className="mt-14">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
