import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './_components/footer/footer'
import Header from './_components/header/header'
import { CartProvider } from './_context/cart'
import AuthProvider from './_providers/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex h-full flex-col">
            <CartProvider>
              <div>
                <Header />
              </div>
              <div className="flex-1">{children}</div>
            </CartProvider>
            <div className="mt-14">
              <Footer />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
